### PR TITLE
Funktionalitet för att följa och avfölja

### LINKED ISSUE #80: Lägga till funktionalitet för att följa och avfölja användare
Som en användare vill jag kunna följa/avfölja andra användare.

Acceptanskrav:
- design i Figma.

### PR DESCRIPTION
**Pull request by mirrenil**
**This PR will:**
- display the number of users the user is following
- correctly toggles the follow button to following on click and adds to database
- if user is already following the button label is "följer"

closes #80

### CODE REVIEW

**Comment by liinneea-a** [comment]
When I visit my profile it says I follow one person. If you look in DB my following list technically has the length of one but its an empty string. This needs to be fixed :)

321554548_701863431649065_2584878043699323344_n

Screenshot 2023-01-11 at 11 52 02

**Comment by liinneea-a** [comment]
I get the error when login in and visit profileScreen. I get this for both user.following.length (as shown in the pic) and for usersFollowersArray.length.

Screenshot 2023-01-11 at 12 00 36

IDEA FOR SOLUTION
My guess is because user.following and usersFollowersArray hasnt or been loaded when the JSX is rendering. Maybe this would work: 
Screenshot 2023-01-11 at 11 56 59

**Comment by liinneea-a** [comment]
Aaaand I also found that the settings menus styling is a bit off 
Screenshot 2023-01-11 at 11 59 38

**Comment by mirrenil** [comment]
> Aaaand I also found that the settings menus styling is a bit off Screenshot 2023-01-11 at 11 59 38

Not sure if you have the latest changes because it does not look like that...

**Comment by mirrenil** [comment]
> I get the error when login in and visit profileScreen. I get this for both user.following.length (as shown in the pic) and for usersFollowersArray.length.
> 
> Screenshot 2023-01-11 at 12 00 36
> 
> IDEA FOR SOLUTION My guess is because user.following and usersFollowersArray hasnt or been loaded when the JSX is rendering. Maybe this would work: Screenshot 2023-01-11 at 11 56 59

That does not fix the problem, will have to come up with a different approach...

**Review by liinneea-a — APPROVED** [review]

**Pull request merged**
